"""Created matches table

Revision ID: 8ce78e51878c
Revises: 0033ea1ffb8b
Create Date: 2024-10-31 01:48:00.013977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ce78e51878c'
down_revision: Union[str, None] = '0033ea1ffb8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_member', sa.Integer(), nullable=False),
    sa.Column('with_member', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['from_member'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['with_member'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_from_member'), 'matches', ['from_member'], unique=False)
    op.create_index(op.f('ix_matches_with_member'), 'matches', ['with_member'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matches_with_member'), table_name='matches')
    op.drop_index(op.f('ix_matches_from_member'), table_name='matches')
    op.drop_table('matches')
    # ### end Alembic commands ###
